# sample config file for postgrest
db-uri = "postgres://username:pwd!@localhost:5432/dbname"
db-schema = "public"
db-anon-role = "anon"
server-host = "*4"
server-port = 3001
# The secret to verify the JWT for authenticated requests with.
# Needs to be 32 characters minimum.
jwt-secret = "reallyreallyreallyreallyverysafe"
jwt-secret-is-base64 = false
